course_ids = {
    "Honors English I": "111",
    "College Prep English I": "112",
    "College Prep Inegrated English I": "113",
    "College Prep Integrated English II": "122",
    "Integrated English I": "114",
    "Honors English II": "121",
    "College Prep English II": "122",
    "Integrated English II": "129",
    "Honors American Literature": "131",
    "Honors World Literature": "132",
    "College Prep American Literature": "135",
    "College Prep Integrated American Literature": "145",
    "College Prep World Literature": "136",
    "College Prep Integrated World Literature": "146",
    "English III": "149",
    "Advanced Placement English Literature & Composition": "151",
    "College Prep Creative Writing": "161",
    "English IV": "169",
    "College Prep Journalism": "171",
    "Advanced Placement Language & Compostion": "181",
    "Honors Algebra I": "214",
    "College Prep Algebra I": "215",
    "College Prep Algebra I Concepts": "213",
    "Concepts Of Algebra I": "219",
    "Honors Geometry": "222",
    "College Prep Geometry": "223",
    "College Prep Geometry Concepts": "206",
    "Geometry Concepts": "249",
    "Mcas 2.0 Prep Grade 10": "220",
    "Honors Algebra II": "217",
    "College Prep Algebra II": "218",
    "College Prep Algebra II Concepts": "216",
    "Algebra II Concepts": "279",
    "Honors Pre-Calculus": "242",
    "College Prep Pre-Calculus": "235",
    "Advanced Placement Statistics & Probability": "247",
    "Honors Statistics & Probability": "241",
    "College Prep Statistics & Probability": "240",
    "Advanced Placement Calculus AB": "251",
    "Advanced Placement Calculus BC": "253",
    "Honors Differential Calculus": "260",
    "Early College Quantitative Reasoning": "256",
    "College Prep Shop Math": "272",
    "College Prep Practical Math": "234",
    "Practical Math": "239",
}